spring:
  data:
    cassandra:
      keyspace-name: tacocloud
      schema-action: recreate-drop-unused
      local-datacenter: datacenter1
      username: tacocloud
      password: s3cr3tP455w0rd
  thymeleaf:
    cache: false

